import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "src", "generated");
const JS_OUT = join(OUT_DIR, "pay.bundle.js");
const ASSETS_OUT = join(OUT_DIR, "pay-assets.ts");
const CSS_SOURCE = join(ROOT, "src", "browser", "pay.css");
const ENTRY = join(ROOT, "src", "browser", "pay-main.ts");

const FORBIDDEN_BROWSER_BUNDLE_MARKERS = [
  "buyer-env",
  "node:fs",
  "privateKeyToAccount",
  "wrapFetchWithPayment",
  "ExactEvmScheme",
  "toClientEvmSigner",
  "createPaymentPayload",
];

async function buildBrowserBundle(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });

  await esbuild.build({
    entryPoints: [ENTRY],
    outfile: JS_OUT,
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    sourcemap: false,
    minify: false,
    legalComments: "none",
  });

  const js = readFileSync(JS_OUT, "utf8");
  const css = readFileSync(CSS_SOURCE, "utf8");

  for (const marker of FORBIDDEN_BROWSER_BUNDLE_MARKERS) {
    if (js.includes(marker)) {
      throw new Error(`Browser bundle contains forbidden marker: ${marker}`);
    }
  }

  const assetsSource = `/* Generated by scripts/build-browser.ts. Do not edit. */\nexport const PAY_JS = ${JSON.stringify(js)};\nexport const PAY_CSS = ${JSON.stringify(css)};\n`;
  writeFileSync(ASSETS_OUT, assetsSource, "utf8");
}

buildBrowserBundle().catch((error) => {
  console.error(error);
  process.exit(1);
});
